[tool.pdm]
[tool.pdm.dev-dependencies]
dev = ["black>=23.1.0", "ruff>=0.0.243", "mypy>=1.0.0", "pre-commit>=3.0.4"]

[project]
name = "torchattack"
version = "0.1.2"
description = "A set of adversarial attacks implemented in PyTorch"
authors = [{ name = "spencerwooo", email = "spencer.woo@outlook.com" }]
dependencies = ["torch>=1.13.1", "torchvision>=0.14.1", "numpy>=1.24.2"]
# 3.11 and above is not supported until PyTorch officially releases 2.0
requires-python = ">=3.10,<3.11"
readme = "README.md"
license = { text = "MIT" }
[project.optional-dependencies]
optional = ["rich>=13.2.0", "scipy>=1.10.0"]

[build-system]
requires = ["pdm-pep517>=1.0"]
build-backend = "pdm.pep517.api"

[tool.ruff]
line-length = 88
select = ["E", "F", "I", "N", "B", "SIM"]

[tool.mypy]
disallow_any_unimported = true
no_implicit_optional = true
check_untyped_defs = true
ignore_missing_imports = true  # Used as torchvision does not ship type hints
# disallow_untyped_defs = true
# warn_return_any = true

[tool.pdm.scripts]
lint = "pre-commit run --all-files"
type-check = "mypy torchattack"
